-- RankYourWebsite: COMPLETE PRODUCTION DATABASE SETUP
-- Run this entire file in your existing project's Supabase SQL Editor.
-- Supports a fresh database or this repository's fully/partly installed schema.
-- Repeatable: retains accounts, websites, scans, reports, payments and settings.
-- Adds missing columns with repository defaults. Incompatible existing rows/types
-- cause a transaction rollback rather than silently inventing or deleting data.
-- Replaces access policies ONLY on the 15 app-owned tables. No demo data is inserted.
-- Payment providers remain disabled on fresh installations; existing flags are preserved.
-- Generated by: node scripts/build-setup-sql.mjs
begin;
set local search_path=public,extensions;
set local lock_timeout='10s';
-- Source: 0001_initial.sql
-- Run in a fresh Supabase project. All mutating RPCs are service-role only.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 first_name text not null default '' check (length(first_name) <= 80),
 referral_code text not null unique default encode(gen_random_bytes(9),'hex'),
 email_verified boolean not null default false,
 is_admin boolean not null default false,
 created_at timestamptz not null default now()
);
alter table public.profiles add column if not exists id uuid primary key references auth.users(id) on delete cascade;
alter table public.profiles add column if not exists first_name text not null default '' check (length(first_name) <= 80);
alter table public.profiles add column if not exists referral_code text not null unique default encode(gen_random_bytes(9),'hex');
alter table public.profiles add column if not exists email_verified boolean not null default false;
alter table public.profiles add column if not exists is_admin boolean not null default false;
alter table public.profiles add column if not exists created_at timestamptz not null default now();
create table if not exists public.website_projects (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade,
 url text not null, name text not null, notes text not null default '', created_at timestamptz not null default now(),
 unique(user_id,url)
);
alter table public.website_projects add column if not exists id uuid primary key default gen_random_uuid();
alter table public.website_projects add column if not exists user_id uuid not null references public.profiles(id) on delete cascade;
alter table public.website_projects add column if not exists url text not null;
alter table public.website_projects add column if not exists name text not null;
alter table public.website_projects add column if not exists notes text not null default '';
alter table public.website_projects add column if not exists created_at timestamptz not null default now();
do $$ begin
 if not exists(select 1 from pg_constraint where conrelid='public.website_projects'::regclass and conname='website_projects_user_id_url_key') then
  alter table public.website_projects add constraint website_projects_user_id_url_key unique(user_id,url);
 end if;
end $$;
create table if not exists public.website_scans (
 id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id) on delete cascade,
 website_project_id uuid references public.website_projects(id) on delete set null,
 guest_hash text, url text not null,
 status text not null default 'queued' check (status in ('queued','running','completed','failed','cancelled')),
 progress integer not null default 0 check (progress between 0 and 100), stage text not null default 'Waiting to start',
 preview jsonb, error text, attempts integer not null default 0,
 lease_until timestamptz, created_at timestamptz not null default now(), completed_at timestamptz,
 check (user_id is not null or guest_hash is not null)
);
alter table public.website_scans add column if not exists id uuid primary key default gen_random_uuid();
alter table public.website_scans add column if not exists user_id uuid references public.profiles(id) on delete cascade;
alter table public.website_scans add column if not exists website_project_id uuid references public.website_projects(id) on delete set null;
alter table public.website_scans add column if not exists guest_hash text;
alter table public.website_scans add column if not exists url text not null;
alter table public.website_scans add column if not exists status text not null default 'queued' check (status in ('queued','running','completed','failed','cancelled'));
alter table public.website_scans add column if not exists progress integer not null default 0 check (progress between 0 and 100);
alter table public.website_scans add column if not exists stage text not null default 'Waiting to start';
alter table public.website_scans add column if not exists preview jsonb;
alter table public.website_scans add column if not exists error text;
alter table public.website_scans add column if not exists attempts integer not null default 0;
alter table public.website_scans add column if not exists lease_until timestamptz;
alter table public.website_scans add column if not exists created_at timestamptz not null default now();
alter table public.website_scans add column if not exists completed_at timestamptz;
do $$ begin
 if not exists(select 1 from pg_constraint where conrelid='public.website_scans'::regclass and conname='website_scans_check') then
  alter table public.website_scans add constraint website_scans_check check (user_id is not null or guest_hash is not null);
 end if;
end $$;
create index if not exists scans_user_date on public.website_scans(user_id,created_at desc);
create index if not exists scans_queue on public.website_scans(status,created_at);
create table if not exists public.audit_issues (
 id uuid primary key default gen_random_uuid(), scan_id uuid not null references public.website_scans(id) on delete cascade,
 code text not null, category text not null, severity text not null,
 deduction integer not null check (deduction between 0 and 100), title text not null, evidence text not null, recommendation text not null,
 unique(scan_id,code)
);
alter table public.audit_issues add column if not exists id uuid primary key default gen_random_uuid();
alter table public.audit_issues add column if not exists scan_id uuid not null references public.website_scans(id) on delete cascade;
alter table public.audit_issues add column if not exists code text not null;
alter table public.audit_issues add column if not exists category text not null;
alter table public.audit_issues add column if not exists severity text not null;
alter table public.audit_issues add column if not exists deduction integer not null check (deduction between 0 and 100);
alter table public.audit_issues add column if not exists title text not null;
alter table public.audit_issues add column if not exists evidence text not null;
alter table public.audit_issues add column if not exists recommendation text not null;
do $$ begin
 if not exists(select 1 from pg_constraint where conrelid='public.audit_issues'::regclass and conname='audit_issues_scan_id_code_key') then
  alter table public.audit_issues add constraint audit_issues_scan_id_code_key unique(scan_id,code);
 end if;
end $$;
create table if not exists public.reports (
 id uuid primary key default gen_random_uuid(), scan_id uuid not null unique references public.website_scans(id) on delete cascade,
 user_id uuid references public.profiles(id) on delete cascade,
 content jsonb not null, unlocked boolean not null default false,
 created_at timestamptz not null default now()
);
alter table public.reports add column if not exists id uuid primary key default gen_random_uuid();
alter table public.reports add column if not exists scan_id uuid not null unique references public.website_scans(id) on delete cascade;
alter table public.reports add column if not exists user_id uuid references public.profiles(id) on delete cascade;
alter table public.reports add column if not exists content jsonb not null;
alter table public.reports add column if not exists unlocked boolean not null default false;
alter table public.reports add column if not exists created_at timestamptz not null default now();
create table if not exists public.referrals (
 id uuid primary key default gen_random_uuid(), referrer_id uuid not null references public.profiles(id) on delete cascade,
 referred_id uuid not null unique references public.profiles(id) on delete cascade,
 status text not null default 'pending' check(status in ('pending','verified','rejected')),
 fraud_indicators jsonb not null default '[]', converted boolean not null default false,
 created_at timestamptz not null default now(), verified_at timestamptz,
 check (referrer_id <> referred_id)
);
alter table public.referrals add column if not exists id uuid primary key default gen_random_uuid();
alter table public.referrals add column if not exists referrer_id uuid not null references public.profiles(id) on delete cascade;
alter table public.referrals add column if not exists referred_id uuid not null unique references public.profiles(id) on delete cascade;
alter table public.referrals add column if not exists status text not null default 'pending' check(status in ('pending','verified','rejected'));
alter table public.referrals add column if not exists fraud_indicators jsonb not null default '[]';
alter table public.referrals add column if not exists converted boolean not null default false;
alter table public.referrals add column if not exists created_at timestamptz not null default now();
alter table public.referrals add column if not exists verified_at timestamptz;
do $$ begin
 if not exists(select 1 from pg_constraint where conrelid='public.referrals'::regclass and conname='referrals_check') then
  alter table public.referrals add constraint referrals_check check (referrer_id <> referred_id);
 end if;
end $$;
create index if not exists referrals_owner on public.referrals(referrer_id,status);
create table if not exists public.discounts (
 id uuid primary key default gen_random_uuid(), user_id uuid not null unique references public.profiles(id) on delete cascade,
 amount_cents integer not null check(amount_cents between 0 and 50), qualified_at timestamptz not null default now()
);
alter table public.discounts add column if not exists id uuid primary key default gen_random_uuid();
alter table public.discounts add column if not exists user_id uuid not null unique references public.profiles(id) on delete cascade;
alter table public.discounts add column if not exists amount_cents integer not null check(amount_cents between 0 and 50);
alter table public.discounts add column if not exists qualified_at timestamptz not null default now();
create table if not exists public.payments (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade,
 report_id uuid not null references public.reports(id) on delete cascade,
 provider text not null check(provider in ('stripe','payfast')),
 status text not null default 'pending' check(status in ('pending','processing','paid','failed','cancelled','refunded')),
 amount_cents integer not null check(amount_cents > 0), currency text not null default 'USD',
 base_usd_cents integer not null, discount_cents integer not null default 0 check(discount_cents between 0 and 50),
 provider_session_id text unique, provider_transaction_id text unique, checkout_url text,
 created_at timestamptz not null default now(), paid_at timestamptz
);
alter table public.payments add column if not exists id uuid primary key default gen_random_uuid();
alter table public.payments add column if not exists user_id uuid not null references public.profiles(id) on delete cascade;
alter table public.payments add column if not exists report_id uuid not null references public.reports(id) on delete cascade;
alter table public.payments add column if not exists provider text not null check(provider in ('stripe','payfast'));
alter table public.payments add column if not exists status text not null default 'pending' check(status in ('pending','processing','paid','failed','cancelled','refunded'));
alter table public.payments add column if not exists amount_cents integer not null check(amount_cents > 0);
alter table public.payments add column if not exists currency text not null default 'USD';
alter table public.payments add column if not exists base_usd_cents integer not null;
alter table public.payments add column if not exists discount_cents integer not null default 0 check(discount_cents between 0 and 50);
alter table public.payments add column if not exists provider_session_id text unique;
alter table public.payments add column if not exists provider_transaction_id text unique;
alter table public.payments add column if not exists checkout_url text;
alter table public.payments add column if not exists created_at timestamptz not null default now();
alter table public.payments add column if not exists paid_at timestamptz;
create index if not exists payments_owner on public.payments(user_id,created_at desc);
create unique index if not exists one_active_payment on public.payments(report_id,provider) where status in ('pending','processing');
create table if not exists public.platform_events (
 id bigint generated always as identity primary key,
 event_key text not null unique, event_type text not null,
 user_id uuid references public.profiles(id) on delete set null,
 website_project_id uuid references public.website_projects(id) on delete set null,
 country_code text check(country_code ~ '^[A-Z]{2}$'), metadata jsonb not null default '{}',
 created_at timestamptz not null default now()
);
alter table public.platform_events add column if not exists id bigint generated always as identity primary key;
alter table public.platform_events add column if not exists event_key text not null unique;
alter table public.platform_events add column if not exists event_type text not null;
alter table public.platform_events add column if not exists user_id uuid references public.profiles(id) on delete set null;
alter table public.platform_events add column if not exists website_project_id uuid references public.website_projects(id) on delete set null;
alter table public.platform_events add column if not exists country_code text check(country_code ~ '^[A-Z]{2}$');
alter table public.platform_events add column if not exists metadata jsonb not null default '{}';
alter table public.platform_events add column if not exists created_at timestamptz not null default now();
create index if not exists events_type_date on public.platform_events(event_type,created_at);
create table if not exists public.platform_totals (
 id boolean primary key default true check(id), registered_users bigint not null default 0,
 completed_scans bigint not null default 0, reports_generated bigint not null default 0
);
alter table public.platform_totals add column if not exists id boolean primary key default true check(id);
alter table public.platform_totals add column if not exists registered_users bigint not null default 0;
alter table public.platform_totals add column if not exists completed_scans bigint not null default 0;
alter table public.platform_totals add column if not exists reports_generated bigint not null default 0;
insert into public.platform_totals(id) values(true) on conflict(id) do nothing;
create table if not exists public.app_settings (
 id boolean primary key default true check(id), base_price_cents integer not null default 200 check(base_price_cents between 100 and 100000),
 referral_discount_cents integer not null default 50 check(referral_discount_cents between 0 and 50),
 referral_threshold integer not null default 5 check(referral_threshold >= 5),
 stripe_enabled boolean not null default false, payfast_enabled boolean not null default false,
 activity_enabled boolean not null default true, ai_enabled boolean not null default true,
 updated_at timestamptz not null default now(), check(base_price_cents > referral_discount_cents)
);
alter table public.app_settings add column if not exists id boolean primary key default true check(id);
alter table public.app_settings add column if not exists base_price_cents integer not null default 200 check(base_price_cents between 100 and 100000);
alter table public.app_settings add column if not exists referral_discount_cents integer not null default 50 check(referral_discount_cents between 0 and 50);
alter table public.app_settings add column if not exists referral_threshold integer not null default 5 check(referral_threshold >= 5);
alter table public.app_settings add column if not exists stripe_enabled boolean not null default false;
alter table public.app_settings add column if not exists payfast_enabled boolean not null default false;
alter table public.app_settings add column if not exists activity_enabled boolean not null default true;
alter table public.app_settings add column if not exists ai_enabled boolean not null default true;
alter table public.app_settings add column if not exists updated_at timestamptz not null default now();
do $$ begin
 if not exists(select 1 from pg_constraint where conrelid='public.app_settings'::regclass and conname='app_settings_check') then
  alter table public.app_settings add constraint app_settings_check check(base_price_cents > referral_discount_cents);
 end if;
end $$;
insert into public.app_settings(id) values(true) on conflict(id) do nothing;
create table if not exists public.ranking_keywords (
 id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade,
 website_project_id uuid not null references public.website_projects(id) on delete cascade,
 keyword text not null check(length(keyword) between 1 and 120), country text not null check(country ~ '^[a-z]{2}$'),
 created_at timestamptz not null default now(), unique(user_id,website_project_id,keyword,country)
);
alter table public.ranking_keywords add column if not exists id uuid primary key default gen_random_uuid();
alter table public.ranking_keywords add column if not exists user_id uuid not null references public.profiles(id) on delete cascade;
alter table public.ranking_keywords add column if not exists website_project_id uuid not null references public.website_projects(id) on delete cascade;
alter table public.ranking_keywords add column if not exists keyword text not null check(length(keyword) between 1 and 120);
alter table public.ranking_keywords add column if not exists country text not null check(country ~ '^[a-z]{2}$');
alter table public.ranking_keywords add column if not exists created_at timestamptz not null default now();
do $$ begin
 if not exists(select 1 from pg_constraint where conrelid='public.ranking_keywords'::regclass and conname='ranking_keywords_user_id_website_project_id_keyword_country_key') then
  alter table public.ranking_keywords add constraint ranking_keywords_user_id_website_project_id_keyword_country_key unique(user_id,website_project_id,keyword,country);
 end if;
end $$;
create table if not exists public.ranking_checks (
 id uuid primary key default gen_random_uuid(), keyword_id uuid not null references public.ranking_keywords(id) on delete cascade,
 position integer check(position > 0), search_depth integer not null default 100, checked_at timestamptz not null default now()
);
alter table public.ranking_checks add column if not exists id uuid primary key default gen_random_uuid();
alter table public.ranking_checks add column if not exists keyword_id uuid not null references public.ranking_keywords(id) on delete cascade;
alter table public.ranking_checks add column if not exists position integer check(position > 0);
alter table public.ranking_checks add column if not exists search_depth integer not null default 100;
alter table public.ranking_checks add column if not exists checked_at timestamptz not null default now();
create table if not exists public.rate_limits (key text primary key, hits integer not null, reset_at timestamptz not null);
alter table public.rate_limits add column if not exists key text primary key;
alter table public.rate_limits add column if not exists hits integer not null;
alter table public.rate_limits add column if not exists reset_at timestamptz not null;
create table if not exists public.webhook_receipts (provider text not null, event_id text not null, created_at timestamptz not null default now(), primary key(provider,event_id));
alter table public.webhook_receipts add column if not exists provider text not null;
alter table public.webhook_receipts add column if not exists event_id text not null;
alter table public.webhook_receipts add column if not exists created_at timestamptz not null default now();
do $$ begin
 if not exists(select 1 from pg_constraint where conrelid='public.webhook_receipts'::regclass and conname='webhook_receipts_pkey') then
  alter table public.webhook_receipts add constraint webhook_receipts_pkey primary key(provider,event_id);
 end if;
end $$;


do $$ declare p record; begin
 for p in select tablename,policyname from pg_policies where schemaname='public'
 and tablename in ('profiles','website_projects','website_scans','audit_issues','reports','referrals','discounts','payments','platform_events','platform_totals','app_settings','ranking_keywords','ranking_checks','rate_limits','webhook_receipts') loop
  execute format('drop policy %I on public.%I',p.policyname,p.tablename);
 end loop;
 -- Old column-level grants survive a table-level REVOKE; remove them explicitly.
 for p in select table_name,column_name from information_schema.columns where table_schema='public'
 and table_name in ('profiles','website_projects','website_scans','audit_issues','reports','referrals','discounts','payments','platform_events','platform_totals','app_settings','ranking_keywords','ranking_checks','rate_limits','webhook_receipts') loop
  execute format('revoke all (%I) on public.%I from public,anon,authenticated',p.column_name,p.table_name);
 end loop;
end $$;
-- Clients can read only their own safe rows, never mutate payment/access/role state.
alter table public.profiles enable row level security;
alter table public.website_projects enable row level security;
alter table public.website_scans enable row level security;
alter table public.audit_issues enable row level security;
alter table public.reports enable row level security;
alter table public.payments enable row level security;
alter table public.referrals enable row level security;
alter table public.discounts enable row level security;
alter table public.platform_events enable row level security;
alter table public.platform_totals enable row level security;
alter table public.app_settings enable row level security;
alter table public.ranking_keywords enable row level security;
alter table public.ranking_checks enable row level security;
alter table public.rate_limits enable row level security;
alter table public.webhook_receipts enable row level security;
revoke all on public.profiles, public.website_projects, public.website_scans, public.audit_issues, public.reports, public.referrals, public.discounts, public.payments, public.platform_events, public.platform_totals, public.app_settings, public.ranking_keywords, public.ranking_checks, public.rate_limits, public.webhook_receipts from public, anon, authenticated;
grant select on public.profiles, public.website_projects, public.website_scans, public.reports, public.audit_issues, public.payments, public.discounts, public.ranking_keywords, public.ranking_checks to authenticated;
create policy own_profile on public.profiles for select to authenticated using (id = (select auth.uid()));
create policy own_projects on public.website_projects for select to authenticated using (user_id = (select auth.uid()));
create policy own_scans on public.website_scans for select to authenticated using (user_id = (select auth.uid()));
create policy own_unlocked_reports on public.reports for select to authenticated using (user_id = (select auth.uid()) and unlocked);
create policy own_unlocked_issues on public.audit_issues for select to authenticated using (exists(select 1 from public.reports r where r.scan_id = audit_issues.scan_id and r.user_id = (select auth.uid()) and r.unlocked));
create policy own_payments on public.payments for select to authenticated using (user_id = (select auth.uid()));
create policy own_discounts on public.discounts for select to authenticated using (user_id = (select auth.uid()));
create policy own_keywords on public.ranking_keywords for select to authenticated using(user_id = (select auth.uid()));
create policy own_rankings on public.ranking_checks for select to authenticated using(exists(select 1 from public.ranking_keywords k where k.id = ranking_checks.keyword_id and k.user_id = (select auth.uid())));

create or replace function public.record_event(p_key text, p_type text, p_user uuid default null, p_project uuid default null) returns void
language plpgsql security definer set search_path = public as $$
begin
 insert into platform_events(event_key,event_type,user_id,website_project_id) values(p_key,p_type,p_user,p_project) on conflict do nothing;
 if found then
  update platform_totals set registered_users = registered_users + (p_type='user_registered')::int,
   completed_scans = completed_scans + (p_type='website_scan_completed')::int,
   reports_generated = reports_generated + (p_type='report_generated')::int where id;
 end if;
end $$;

create or replace function public.sync_auth_user() returns trigger language plpgsql security definer set search_path = public as $$
declare ref_id uuid;
begin
 if TG_OP = 'INSERT' then
  insert into profiles(id,first_name,email_verified) values(new.id,left(coalesce(new.raw_user_meta_data->>'first_name',''),80),new.email_confirmed_at is not null);
  select id into ref_id from profiles where referral_code = new.raw_user_meta_data->>'referral_code' and id <> new.id and email_verified;
  if ref_id is not null then insert into referrals(referrer_id,referred_id) values(ref_id,new.id) on conflict do nothing; end if;
 end if;
 if new.email_confirmed_at is not null then
  update profiles set email_verified=true where id=new.id;
  perform record_event('registered:'||new.id,'user_registered',new.id);
  perform verify_referral(new.id);
 end if;
 return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.sync_auth_user();
drop trigger if exists on_auth_user_verified on auth.users;
create trigger on_auth_user_verified after update of email_confirmed_at on auth.users for each row execute function public.sync_auth_user();

create or replace function public.verify_referral(p_user uuid) returns void language plpgsql security definer set search_path=public as $$
declare r referrals; s app_settings;
begin
 if not exists(select 1 from profiles where id=p_user and email_verified) or not exists(select 1 from website_scans where user_id=p_user and status='completed') then return; end if;
 update referrals set status='verified',verified_at=now() where referred_id=p_user and status='pending' returning * into r;
 if found then
  perform record_event('referral:'||r.id,'referral_verified',r.referrer_id);
  select * into s from app_settings where id;
  if (select count(*) from referrals where referrer_id=r.referrer_id and status='verified') >= s.referral_threshold then
   insert into discounts(user_id,amount_cents) values(r.referrer_id,s.referral_discount_cents) on conflict(user_id) do nothing;
  end if;
 end if;
end $$;

create or replace function public.claim_scan(p_scan uuid, p_guest text, p_user uuid) returns boolean language plpgsql security definer set search_path=public as $$
declare s website_scans; project uuid;
begin
 select * into s from website_scans where id=p_scan for update;
 if s.user_id is not null then return s.user_id=p_user; end if;
 if s.guest_hash is distinct from p_guest or s.created_at < now()-interval '24 hours' then return false; end if;
 insert into website_projects(user_id,url,name) values(p_user,s.url,s.url) on conflict(user_id,url) do update set url=excluded.url returning id into project;
 update website_scans set user_id=p_user,website_project_id=project,guest_hash=null where id=p_scan;
 update reports set user_id=p_user where scan_id=p_scan;
 perform verify_referral(p_user);
 return true;
end $$;

create or replace function public.take_scan(p_id uuid default null) returns setof public.website_scans language plpgsql security definer set search_path=public as $$
declare picked uuid;
begin
 update website_scans set status='failed',stage='Scan timed out',error='The scan timed out. Please start a new scan.'
  where status='running' and lease_until<now() and attempts>=3;
 select id into picked from website_scans where (p_id is null or id=p_id) and (status='queued' or (status='running' and lease_until<now() and attempts<3)) order by created_at for update skip locked limit 1;
 if picked is null then return; end if;
 return query update website_scans set status='running',attempts=attempts+1,lease_until=now()+interval '4 minutes',stage='Validating website',progress=5 where id=picked returning *;
end $$;

create or replace function public.complete_scan(p_id uuid, p_attempt integer, p_preview jsonb, p_content jsonb, p_issues jsonb) returns boolean language plpgsql security definer set search_path=public as $$
declare s website_scans; issue jsonb;
begin
 select * into s from website_scans where id=p_id for update;
 if s.status <> 'running' or s.attempts <> p_attempt then return false; end if;
 insert into reports(scan_id,user_id,content) values(s.id,s.user_id,p_content) on conflict(scan_id) do nothing;
 for issue in select * from jsonb_array_elements(p_issues) loop
  insert into audit_issues(scan_id,code,category,severity,deduction,title,evidence,recommendation)
  values(s.id,issue->>'code',issue->>'category',issue->>'severity',(issue->>'deduction')::int,issue->>'title',issue->>'evidence',issue->>'recommendation') on conflict do nothing;
 end loop;
 update website_scans set status='completed',preview=p_preview,progress=100,stage='Report ready',completed_at=now(),lease_until=null where id=p_id;
 perform record_event('scan:'||s.id,'website_scan_completed',s.user_id,s.website_project_id);
 perform record_event('report:'||s.id,'report_generated',s.user_id,s.website_project_id);
 if s.website_project_id is not null and exists(select 1 from website_scans where website_project_id=s.website_project_id and id<>s.id and status='completed') then
  perform record_event('rescan:'||s.id,'rescan_completed',s.user_id,s.website_project_id);
 end if;
 if s.user_id is not null then perform verify_referral(s.user_id); end if;
 return true;
end $$;

-- Reservation locks serialize concurrent checkout requests for a report.
create or replace function public.reserve_payment(p_user uuid,p_report uuid,p_provider text,p_pkr_rate numeric default null) returns public.payments language plpgsql security definer set search_path=public as $$
declare r reports; s app_settings; p payments; discount integer:=0; amount integer; curr text:='USD';
begin
 select * into r from reports where id=p_report and user_id=p_user for update;
 if not found or r.unlocked then raise exception 'Report unavailable'; end if;
 select * into s from app_settings where id;
 if not exists(select 1 from profiles where id=p_user and email_verified) then raise exception 'Verify your email first'; end if;
 if not ((p_provider='stripe' and s.stripe_enabled) or (p_provider='payfast' and s.payfast_enabled)) then raise exception 'Provider unavailable'; end if;
 update payments set status='cancelled' where report_id=p_report and provider=p_provider and status in ('pending','processing') and created_at<now()-interval '24 hours';
 select * into p from payments where report_id=p_report and provider=p_provider and status in ('pending','processing');
 if found then return p; end if;
 if (select count(*) from referrals where referrer_id=p_user and status='verified') >= s.referral_threshold then discount:=s.referral_discount_cents; end if;
 amount:=s.base_price_cents-discount;
 if p_provider='payfast' then
  if p_pkr_rate is null or p_pkr_rate <= 0 then raise exception 'PKR conversion rate not configured'; end if;
  amount:=round(amount*p_pkr_rate); curr:='PKR';
 end if;
 insert into payments(user_id,report_id,provider,amount_cents,currency,base_usd_cents,discount_cents)
 values(p_user,p_report,p_provider,amount,curr,s.base_price_cents,discount) returning * into p;
 return p;
end $$;

create or replace function public.fulfill_payment(p_payment uuid,p_provider text,p_event text,p_transaction text,p_amount integer,p_currency text) returns boolean language plpgsql security definer set search_path=public as $$
declare p payments;
begin
 select * into p from payments where id=p_payment for update;
 if not found or p.provider<>p_provider or p.amount_cents<>p_amount or p.currency<>upper(p_currency) or p.status='refunded' then raise exception 'Payment mismatch'; end if;
 insert into webhook_receipts(provider,event_id) values(p_provider,p_event) on conflict do nothing;
 if not found then return false; end if;
 if p.status='paid' then return false; end if;
 update payments set status='paid',provider_transaction_id=p_transaction,paid_at=now() where id=p.id;
 update reports set unlocked=true where id=p.report_id and user_id=p.user_id;
 update referrals set converted=true where referred_id=p.user_id and status='verified';
 perform record_event('unlock:'||p.id,'report_unlocked',p.user_id);
 return true;
end $$;
create or replace function public.refund_payment(p_transaction text,p_event text) returns void language plpgsql security definer set search_path=public as $$
declare p payments;
begin
 select * into p from payments where provider_transaction_id=p_transaction for update;
 if not found then return; end if;
 insert into webhook_receipts(provider,event_id) values(p.provider,p_event) on conflict do nothing;
 if not found then return; end if;
 update payments set status='refunded' where id=p.id;
 update reports set unlocked=exists(select 1 from payments where report_id=p.report_id and status='paid') where id=p.report_id;
end $$;

create or replace function public.consume_rate(p_key text,p_limit integer,p_window integer) returns boolean language plpgsql security definer set search_path=public as $$
declare n integer;
begin
 insert into rate_limits(key,hits,reset_at) values(p_key,1,now()+make_interval(secs=>p_window))
 on conflict(key) do update set hits=case when rate_limits.reset_at<now() then 1 else rate_limits.hits+1 end,
 reset_at=case when rate_limits.reset_at<now() then now()+make_interval(secs=>p_window) else rate_limits.reset_at end returning hits into n;
 return n<=p_limit;
end $$;


grant all on public.profiles, public.website_projects, public.website_scans, public.audit_issues, public.reports, public.referrals, public.discounts, public.payments, public.platform_events, public.platform_totals, public.app_settings, public.ranking_keywords, public.ranking_checks, public.rate_limits, public.webhook_receipts to service_role;
grant usage,select on sequence public.platform_events_id_seq to service_role;



-- Source: 0002_admin_analytics.sql
create or replace function public.admin_analytics(p_days integer default 30) returns jsonb language sql security definer set search_path=public as $$
with cutoff as (select case when p_days=0 then '-infinity'::timestamptz else date_trunc('day',now())-make_interval(days=>greatest(p_days-1,0)) end as d),
growth as (
 select date_trunc('day',created_at)::date as day,
 count(*) filter(where event_type='user_registered') as users,
 count(*) filter(where event_type='website_scan_completed') as scans,
 count(*) filter(where event_type='report_generated') as reports
 from platform_events,cutoff where created_at>=cutoff.d group by 1
), revenue as (
 select date_trunc('day',paid_at)::date as day,sum(base_usd_cents-discount_cents) as usd_cents
 from payments,cutoff where status='paid' and paid_at>=cutoff.d group by 1
)
select jsonb_build_object(
 'totals',(select to_jsonb(t)-'id' from platform_totals t where id),
 'newUsersToday',(select count(*) from platform_events where event_type='user_registered' and created_at>=date_trunc('day',now())),
 'newUsersWeek',(select count(*) from platform_events where event_type='user_registered' and created_at>=date_trunc('week',now())),
 'newUsersMonth',(select count(*) from platform_events where event_type='user_registered' and created_at>=date_trunc('month',now())),
 'scans',(select jsonb_build_object('total',count(*),'successful',count(*) filter(where status='completed'),'failed',count(*) filter(where status='failed')) from website_scans,cutoff where created_at>=cutoff.d),
 'payments',(select jsonb_build_object('total',count(*),'paid',count(*) filter(where status='paid'),'failed',count(*) filter(where status='failed'),'discountsUsed',count(*) filter(where status='paid' and discount_cents>0),'revenueUsdCents',coalesce(sum(base_usd_cents-discount_cents) filter(where status='paid'),0)) from payments,cutoff where created_at>=cutoff.d),
 'reports',(select jsonb_build_object('total',count(*),'paid',count(*) filter(where unlocked),'free',count(*) filter(where not unlocked)) from reports,cutoff where created_at>=cutoff.d),
 'referralConversions',(select count(*) from referrals,cutoff where converted and verified_at>=cutoff.d),
 'growth',coalesce((select jsonb_agg(jsonb_build_object('day',coalesce(g.day,r.day),'users',coalesce(g.users,0),'scans',coalesce(g.scans,0),'reports',coalesce(g.reports,0),'revenueUsdCents',coalesce(r.usd_cents,0)) order by coalesce(g.day,r.day)) from growth g full join revenue r using(day)),'[]'::jsonb)
);
$$;
revoke all on function public.admin_analytics(integer) from public,anon,authenticated;
grant execute on function public.admin_analytics(integer) to service_role;


-- Source: 0003_personal_metrics.sql
create or replace function public.personal_metrics(p_user uuid) returns jsonb language sql security definer set search_path=public as $$
 select jsonb_build_object(
 'websites',(select count(*) from website_projects where user_id=p_user),
 'scans',(select count(*) from website_scans where user_id=p_user and status='completed'),
 'reports',(select count(*) from reports where user_id=p_user and unlocked),
 'average',(select round(avg((preview->>'overall')::numeric)) from website_scans where user_id=p_user and status='completed'),
 'referrals',(select count(*) from referrals where referrer_id=p_user and status='verified'),
 'payments',(select count(*) from payments where user_id=p_user and status='paid')
 );
$$;
revoke all on function public.personal_metrics(uuid) from public,anon,authenticated;
grant execute on function public.personal_metrics(uuid) to service_role;


-- Source: 0004_public_growth_and_maintenance.sql
create or replace function public.public_growth() returns jsonb language sql security definer set search_path=public as $$
 with days as (select generate_series(date_trunc('day',now())-interval '13 days',date_trunc('day',now()),interval '1 day') as bucket),
 counts as (select date_trunc('day',created_at) as bucket,count(*) as n from platform_events where event_type='website_scan_completed' and created_at>=date_trunc('day',now())-interval '13 days' group by 1)
 select jsonb_agg(jsonb_build_object('date',days.bucket::date,'scans',coalesce(counts.n,0)) order by days.bucket) from days left join counts using(bucket);
$$;
create or replace function public.maintain_platform() returns void language plpgsql security definer set search_path=public as $$
begin
 delete from rate_limits where reset_at<now()-interval '1 day';
 -- Unsaved anonymous reports are never permanently retained.
 delete from website_scans where user_id is null and created_at<now()-interval '7 days';
end $$;
revoke all on function public.public_growth() from public,anon,authenticated;
revoke all on function public.maintain_platform() from public,anon,authenticated;
grant execute on function public.public_growth() to service_role;
grant execute on function public.maintain_platform() to service_role;


-- Source: 0005_production_readiness.sql
-- Only genuine auth/application records are backfilled. No sample users or scans.
create or replace function public.sync_auth_user() returns trigger
language plpgsql security definer set search_path=public as $$
declare ref_id uuid;
begin
 insert into profiles(id,first_name,email_verified)
 values(new.id,left(coalesce(new.raw_user_meta_data->>'first_name',''),80),new.email_confirmed_at is not null)
 on conflict(id) do nothing;
 if TG_OP='INSERT' then
  select id into ref_id from profiles where referral_code=new.raw_user_meta_data->>'referral_code' and id<>new.id and email_verified;
  if ref_id is not null then
   insert into referrals(referrer_id,referred_id) values(ref_id,new.id) on conflict do nothing;
  end if;
 end if;
 update profiles set email_verified=(new.email_confirmed_at is not null) where id=new.id;
 if new.email_confirmed_at is not null then
  perform record_event('registered:'||new.id,'user_registered',new.id);
  perform verify_referral(new.id);
 end if;
 return new;
end $$;

-- Users created before the application tables were installed can still sign in.
insert into public.profiles(id,first_name,email_verified)
select id,left(coalesce(raw_user_meta_data->>'first_name',''),80),email_confirmed_at is not null
from auth.users on conflict(id) do nothing;
update public.profiles p set email_verified=(u.email_confirmed_at is not null)
from auth.users u where u.id=p.id;
insert into public.referrals(referrer_id,referred_id)
select p.id,u.id from auth.users u join public.profiles p
on p.referral_code=u.raw_user_meta_data->>'referral_code'
where p.id<>u.id and p.email_verified on conflict do nothing;

insert into public.platform_events(event_key,event_type,user_id,created_at)
select 'registered:'||id,'user_registered',id,email_confirmed_at from auth.users
where email_confirmed_at is not null on conflict(event_key) do nothing;
insert into public.platform_events(event_key,event_type,user_id,website_project_id,created_at)
select 'scan:'||id,'website_scan_completed',user_id,website_project_id,coalesce(completed_at,created_at)
from public.website_scans where status='completed' on conflict(event_key) do nothing;
insert into public.platform_events(event_key,event_type,user_id,created_at)
select 'report:'||scan_id,'report_generated',user_id,created_at from public.reports
on conflict(event_key) do nothing;
update public.platform_totals set
registered_users=(select count(*) from public.platform_events where event_type='user_registered'),
completed_scans=(select count(*) from public.platform_events where event_type='website_scan_completed'),
reports_generated=(select count(*) from public.platform_events where event_type='report_generated') where id;
do $$ declare u uuid; begin
 for u in select referred_id from public.referrals where status='pending' loop
  perform public.verify_referral(u);
 end loop;
end $$;

-- Owners may read referral progress, but never invitee IDs or fraud metadata.
drop policy if exists own_referral_progress on public.referrals;
create policy own_referral_progress on public.referrals for select to authenticated
using(referrer_id=(select auth.uid()));
revoke all on public.referrals from anon,authenticated;
grant select(id,referrer_id,status,converted,created_at,verified_at) on public.referrals to authenticated;

create index if not exists reports_owner_date on public.reports(user_id,created_at desc);
create index if not exists projects_owner_date on public.website_projects(user_id,created_at desc);
create index if not exists events_owner_date on public.platform_events(user_id,created_at desc);
create index if not exists ranking_checks_keyword_date on public.ranking_checks(keyword_id,checked_at desc);

-- Read-only diagnostics. Accessible only with the server credential.
create or replace function public.setup_status() returns jsonb
language sql security definer set search_path=public as $$
select jsonb_build_object('schemaVersion',5,'rlsEnabled',
 (select count(*)=15 and bool_and(relrowsecurity) from pg_class
 where relnamespace='public'::regnamespace and relname in
 ('profiles','website_projects','website_scans','audit_issues','reports','referrals','discounts','payments',
 'platform_events','platform_totals','app_settings','ranking_keywords','ranking_checks','rate_limits','webhook_receipts')),
 'authTriggersEnabled',(select count(*)=2 and bool_and(tgenabled<>'D') from pg_trigger
 where tgrelid='auth.users'::regclass and tgname in ('on_auth_user_created','on_auth_user_verified')),
 'settingsPresent',exists(select 1 from app_settings where id),
 'totalsPresent',exists(select 1 from platform_totals where id));
$$;
revoke all on function public.setup_status() from public,anon,authenticated;
grant execute on function public.setup_status() to service_role;
revoke all on function public.sync_auth_user() from public,anon,authenticated;
grant execute on function public.sync_auth_user() to service_role;

-- Scope function permissions to this application, never unrelated project RPCs.
do $$ declare f record; begin
 for f in select oid::regprocedure as signature from pg_proc where pronamespace='public'::regnamespace
 and proname in ('record_event','sync_auth_user','verify_referral','claim_scan','take_scan','complete_scan','reserve_payment','fulfill_payment','refund_payment','consume_rate','admin_analytics','personal_metrics','public_growth','maintain_platform','setup_status') loop
  execute format('revoke all on function %s from public,anon,authenticated',f.signature);
  execute format('grant execute on function %s to service_role',f.signature);
 end loop;
end $$;
notify pgrst, 'reload schema';
commit;
-- A successful run returns schemaVersion=5 and all boolean fields=true.
select public.setup_status();
