import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Globe2, Search, FileText, Gauge, Gift, CreditCard, ArrowUpRight, Plus, CheckCircle2 } from 'lucide-react';
import type { dashboardData } from '@/lib/dashboard';
import type { Settings } from '@/types';
import { brand,money } from '@/lib/config';
import { Empty } from '@/components/ui';
import { Community } from '@/components/community';
import { ScanForm } from '@/components/scan-form';
import { Logout } from '@/components/auth-form';
import { EmailVerification,ProfileForm,ProjectForm,RankingForm,ReferralShare,SecuritySettings } from '@/components/dashboard/forms';

const names:Record<string,string>={overview:'Overview',analyze:'Analyze a website',websites:'My websites',reports:'My reports',rankings:'Ranking tracker',referrals:'Grow together. Save together.',billing:'Billing & payments',account:'Your account',settings:'Settings'};
export function DashboardContent({d,settings,section='overview',email,initialUrl='',demo=false}:{d:Awaited<ReturnType<typeof dashboardData>>;settings:Settings;section?:string;email:string;initialUrl?:string;demo?:boolean}){if(!names[section])notFound();const base=demo?'/demo/dashboard':'/dashboard';const reportLink=(id:string)=>demo?'/demo/report':`/report/${id}`;const scanLink=(id:string,status:string)=>demo?'/demo/report':`/${status==='completed'?'report':'scan'}/${id}`;const count=Number(d.metrics.referrals);const labels:Record<string,string>={user_registered:'Account verified',website_scan_completed:'Website scan completed',report_generated:'Report generated',report_unlocked:'Payment verified — report unlocked',referral_verified:'Referral verified',rescan_completed:'Website re-scanned'};
 const scansTable=<div className="table-wrap"><table><thead><tr><th>WEBSITE</th><th>DATE</th><th>STATUS</th><th>SCORE</th><th/></tr></thead><tbody>{d.scans.map(s=><tr key={s.id}><td>{s.url}</td><td>{new Date(s.created_at).toLocaleDateString()}</td><td><span className={`badge ${s.status}`}>{s.status}</span></td><td>{s.preview?.overall??'—'}</td><td><Link className="inline-link" href={scanLink(s.id,s.status)}><ArrowUpRight size={15}/><span className="sr-only">View scan</span></Link></td></tr>)}</tbody></table>{!d.scans.length&&<Empty>Your first insight is one scan away. <Link href={`${base}/analyze`} className="inline-link">Analyze a website</Link>.</Empty>}</div>;
 return <><div className="workspace-intro"><div><div className="eyebrow">YOUR SPACE TO GROW</div><h1>{section==='overview'?`Welcome back, ${d.profile.first_name||'there'}.`:names[section]}</h1><p>{section==='overview'?'A little clarity. A better next move. Here’s your website overview.':demo?'Sample workspace. Explore every screen.':'Real data. Private insights. Practical next steps.'}</p></div>{section==='account'?<Logout/>:<Link className="button primary" href={`${base}/analyze`}><Plus size={14}/> New scan</Link>}</div>{!d.profile.email_verified&&<EmailVerification email={email}/>}
 {section==='overview'&&<><div className="metric-grid">{[{label:'My websites',value:d.metrics.websites,Icon:Globe2},{label:'Completed scans',value:d.metrics.scans,Icon:Search},{label:'Reports unlocked',value:d.metrics.reports,Icon:FileText},{label:'Average score',value:d.metrics.average===null?'—':`${d.metrics.average}/100`,Icon:Gauge},{label:'Verified referrals',value:`${count}/${settings.referral_threshold}`,Icon:Gift},{label:'Successful payments',value:d.metrics.payments,Icon:CreditCard}].map(m=><div className="metric-card" key={m.label}><small>{m.label}<m.Icon size={16}/></small><strong>{m.value}</strong></div>)}</div><section className="panel"><div className="panel-head"><h2>Your scan history</h2><Link className="inline-link" href={`${base}/reports`} style={{fontSize:11}}>View reports →</Link></div>{scansTable}</section><div className="grid-2"><section className="panel"><h2>Recent activity</h2>{d.events.length?<div className="activity-list">{d.events.map((event,i)=><div className="activity-item" key={i}><CheckCircle2 size={14}/><span>{labels[event.event_type]||'Account activity'}</span><small>{new Date(event.created_at).toLocaleDateString()}</small></div>)}</div>:<Empty>Your activity will appear here after your first scan.</Empty>}</section><section className="panel"><div className="eyebrow"><Gift size={14}/> SHARE A LITTLE CLARITY</div><h2>Better websites, together.</h2><p style={{fontSize:12}}>Refer {settings.referral_threshold} verified users and save {money(settings.referral_discount_cents)} on your full report.</p><div className="ref-dots">{Array.from({length:Math.min(settings.referral_threshold,10)},(_,i)=><i key={i} className={i<count?'verified':''}/>)}</div><p style={{fontSize:12}}>{count} / {settings.referral_threshold} verified referrals</p><Link className="button small" href={`${base}/referrals`}>Your referral link <ArrowUpRight size={13}/></Link></section></div>{demo?<div className="notice">Community statistics use real platform activity. Connect Supabase to see live counters; sample workspace data is never added to public statistics.</div>:<Community dashboard/>}{d.profile.is_admin&&<Link className="button" href={demo?'/demo/admin':'/admin'} style={{marginTop:20}}>Open admin analytics</Link>}</>}
 {section==='analyze'&&<><section className="panel"><h2>What could your website do better?</h2><p style={{fontSize:13}}>Enter a public webpage you’re authorized to analyze. We’ll check its initial HTML, technical signals, content structure, and more.</p><ScanForm initialUrl={initialUrl}/><div className="notice">Your free scan includes the overall score, all category scores, and your top three priorities. Full reports cost {money(settings.base_price_cents)}.</div></section><section className="panel"><h2>Previous scans</h2>{scansTable}</section></>}
 {section==='websites'&&<>{!d.projects.length?<section className="panel"><Empty>Analyze your first website to add it here.</Empty></section>:<div className="grid-2">{d.projects.map(p=><section className="panel" key={p.id}><div className="eyebrow"><Globe2 size={14}/>{new URL(p.url).hostname}</div><h2>{p.name}</h2><ProjectForm id={p.id} name={p.name} notes={p.notes}/><Link className="button small" style={{marginTop:20}} href={`${base}/analyze?url=${encodeURIComponent(p.url)}`}>Re-scan website</Link><div className="activity-list">{d.scans.filter(s=>s.website_project_id===p.id).slice(0,5).map(s=><Link className="activity-item" href={scanLink(s.id,s.status)} key={s.id}><span>{new Date(s.created_at).toLocaleDateString()}</span><small>{s.preview?.overall??'—'} / 100 · {s.status}</small></Link>)}</div></section>)}</div>}</>}
 {section==='reports'&&<section className="panel"><h2>Your report library</h2><div className="table-wrap"><table><thead><tr><th>WEBSITE</th><th>GENERATED</th><th>ACCESS</th><th/></tr></thead><tbody>{d.reports.map(r=><tr key={r.id}><td>{d.scans.find(s=>s.id===r.scan_id)?.url||'Website report'}</td><td>{new Date(r.created_at).toLocaleDateString()}</td><td><span className={`badge ${r.unlocked?'paid':''}`}>{r.unlocked?'Full report':'Free preview'}</span></td><td><Link className="inline-link" href={reportLink(r.scan_id)}>Open report →</Link></td></tr>)}</tbody></table></div>{!d.reports.length&&<Empty>Completed scans will appear here as reports.</Empty>}</section>}
 {section==='referrals'&&<><section className="panel"><div className="eyebrow">YOUR NEXT REPORT, FOR LESS</div><h2>Save {money(settings.referral_discount_cents)} with {settings.referral_threshold} verified referrals.</h2><p style={{fontSize:13}}>A referral qualifies after a unique new user signs up through your link, verifies their email, and completes a successful website scan. Self-referrals and duplicate accounts do not qualify.</p><div className="ref-dots">{Array.from({length:Math.min(settings.referral_threshold,10)},(_,i)=><i className={i<count?'verified':''} key={i}/>)}</div><p>{count} / {settings.referral_threshold} verified · {count>=settings.referral_threshold?'Discount available':'Keep sharing your link'}</p><ReferralShare link={`${brand.domain}/r/${d.profile.referral_code}`}/><div className="notice">Normal price {money(settings.base_price_cents)} → qualified price {money(settings.base_price_cents-settings.referral_discount_cents)}. Maximum discount: {money(settings.referral_discount_cents)} per purchase.</div></section><section className="panel"><h2>Referral activity</h2><p style={{fontSize:12}}>We show status only to protect your invitees’ privacy.</p>{d.referrals.length?<table><thead><tr><th>JOINED</th><th>STATUS</th><th>CONVERTED</th></tr></thead><tbody>{d.referrals.map((r,i)=><tr key={i}><td>{new Date(r.created_at).toLocaleDateString()}</td><td>{r.status}</td><td>{r.converted?'Yes':'Not yet'}</td></tr>)}</tbody></table>:<Empty>No referrals yet. Share your link to get started.</Empty>}</section></>}
 {section==='billing'&&<section className="panel"><h2>Payment history</h2><div className="table-wrap"><table><thead><tr><th>DATE</th><th>PROVIDER</th><th>AMOUNT</th><th>STATUS</th></tr></thead><tbody>{d.payments.map(p=><tr key={p.id}><td>{new Date(p.created_at).toLocaleDateString()}</td><td>{p.provider}</td><td>{money(p.amount_cents,p.currency)}</td><td><span className={`badge ${p.status}`}>{p.status}</span></td></tr>)}</tbody></table></div>{!d.payments.length&&<Empty>No payments yet. Start with a free scan.</Empty>}<p style={{fontSize:11,marginTop:24}}>Payments are processed by the configured provider. Refund questions? <Link className="inline-link" href="/refunds">Read the refund policy</Link>.</p></section>}
 {section==='rankings'&&<>{!process.env.SERPAPI_KEY&&<div className="notice">Live keyword position tracking requires a ranking data provider. You can save your keywords now. Website diagnostic scores are not Google rankings.</div>}<section className="panel"><h2>Track a keyword</h2><RankingForm projects={d.projects} connected={!!process.env.SERPAPI_KEY}/></section><section className="panel"><h2>Saved keywords and history</h2>{d.keywords.length?d.keywords.map(k=><div key={k.id} className="finding"><h3 style={{fontSize:15}}>{k.keyword} <span className="badge">{k.country.toUpperCase()}</span></h3><p>{d.projects.find(p=>p.id===k.website_project_id)?.name}</p>{k.ranking_checks.length?<table><thead><tr><th>CHECKED</th><th>ORGANIC POSITION</th><th>RESULTS RETURNED</th></tr></thead><tbody>{[...k.ranking_checks].sort((a,b)=>Date.parse(b.checked_at)-Date.parse(a.checked_at)).slice(0,10).map((r,i)=><tr key={i}><td>{new Date(r.checked_at).toLocaleDateString()}</td><td>{r.position??'Not found in returned results'}</td><td>{r.search_depth}</td></tr>)}</tbody></table>:<small>No ranking measurements yet.</small>}</div>):<Empty>Add a keyword to begin tracking.</Empty>}<small style={{display:'block',marginTop:15}}>Re-submit a saved keyword to record a new measurement. Results reflect the provider’s returned organic results, country, and check time.</small></section></>}
 {section==='account'&&<section className="panel" style={{maxWidth:600}}><h2>Profile details</h2><ProfileForm name={d.profile.first_name} email={email}/></section>}
 {section==='settings'&&<section className="panel" style={{maxWidth:700}}><h2>Security & privacy</h2><SecuritySettings/></section>}
 {['reports','websites','billing','overview'].includes(section)&&<small style={{display:'block',marginTop:18}}>Lists show your latest 200 records. Overview totals include all your records.</small>}
 </>;}
