'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Copy, Check, Mail, ExternalLink } from 'lucide-react';
import { browserDb } from '@/lib/supabase/browser';
export function ProfileForm({name,email}:{name:string;email:string}){const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);const router=useRouter();return <form onSubmit={async e=>{e.preventDefault();setBusy(true);const firstName=new FormData(e.currentTarget).get('name');try{const r=await fetch('/api/account',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'profile',firstName})});const d=await r.json();setMessage(r.ok?'Profile updated.':d.error);if(r.ok)router.refresh();}catch{setMessage('Unable to update profile.');}setBusy(false);}}><label className="field">First name<input className="input" name="name" defaultValue={name} required maxLength={80}/></label><label className="field">Account email<input className="input" value={email} readOnly/></label><button className="button primary" disabled={busy}>Save profile</button>{message&&<div className="notice" role="status">{message}</div>}</form>;}
export function ProjectForm({id,name,notes}:{id:string;name:string;notes:string}){const [message,setMessage]=useState('');return <form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const r=await fetch('/api/account',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'project',id,name:f.get('name'),notes:f.get('notes')})});setMessage(r.ok?'Saved.':'Unable to save changes.');}catch{setMessage('Unable to save changes.');}}}><label className="field">Website name<input className="input" name="name" defaultValue={name} required maxLength={120}/></label><label className="field">Private notes<textarea className="input" name="notes" defaultValue={notes} maxLength={4000}/></label><button className="button small">Save notes</button>{message&&<small role="status"> {message}</small>}</form>;}
export function ReferralShare({link}:{link:string}){const [copied,setCopied]=useState(false);const text=`Get a clearer picture of your website: ${link}`;return <><label className="field">Your unique referral link<div style={{display:'flex',gap:8}}><input className="input" value={link} readOnly/><button className="button" onClick={async()=>{try{await navigator.clipboard.writeText(link);setCopied(true);}catch{setCopied(false);}}}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'Copied':'Copy'}</button></div></label><div className="share-grid">{[{name:'WhatsApp',url:`https://wa.me/?text=${encodeURIComponent(text)}`},{name:'Facebook',url:`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(link)}`},{name:'LinkedIn',url:`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(link)}`},{name:'X',url:`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`}].map(s=><a key={s.name} className="button small" href={s.url} target="_blank" rel="noopener noreferrer">{s.name}<ExternalLink size={11}/></a>)}<a className="button small" href={`mailto:?subject=${encodeURIComponent('A clearer picture of your website')}&body=${encodeURIComponent(text)}`}><Mail size={12}/> Email</a></div></>;}
export function RankingForm({projects,connected}:{projects:{id:string;name:string}[];connected:boolean}){const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);const router=useRouter();return <form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');const f=new FormData(e.currentTarget);try{const r=await fetch('/api/rankings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});const d=await r.json();setMessage(d.message||d.error);if(r.ok)router.refresh();}catch{setMessage('Unable to contact the ranking service.');}setBusy(false);}}><div className="grid-2"><label className="field">Website<select className="input" name="websiteId" required><option value="">Choose a website</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field">Target keyword<input className="input" name="keyword" required maxLength={120} placeholder="e.g. handmade furniture"/></label></div><label className="field">Country<select className="input" name="country"><option value="pk">Pakistan</option><option value="us">United States</option><option value="gb">United Kingdom</option><option value="ca">Canada</option><option value="au">Australia</option><option value="ae">United Arab Emirates</option><option value="in">India</option></select></label><button className="button primary" disabled={busy||!projects.length}>{busy?'Checking…':connected?'Save and check position':'Save keyword'}</button>{message&&<div className="notice" role="status">{message}</div>}</form>;}
export function EmailVerification({email}:{email:string}){const [message,setMessage]=useState('');return <div className="notice">Verify your email before checkout or referral qualification. <button className="button small" onClick={async()=>{const {error}=await browserDb().auth.resend({type:'signup',email,options:{emailRedirectTo:`${window.location.origin}/auth/callback`}});setMessage(error?error.message:'Verification email sent.');}}>Resend verification</button>{message&&<p role="status">{message}</p>}</div>;}
export function SecuritySettings(){return <><p style={{fontSize:13}}>Keep your account secure with a unique password. Report and payment access is checked on the server for every request.</p><Link className="button" href="/auth/forgot-password">Change password by email</Link><div className="notice">Only essential session and referral cookies are used. There are no advertising trackers or optional analytics cookies to configure.</div></>;}
