import { beforeAll,afterAll,describe,it,expect } from 'vitest';
import { PGlite } from '@electric-sql/pglite';
import { pgcrypto } from '@electric-sql/pglite/contrib/pgcrypto';
import { readFileSync,readdirSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
let db:PGlite;
async function one<T=Record<string,unknown>>(sql:string,params:unknown[]=[]){return (await db.query<T>(sql,params)).rows[0];}
async function user(verified=true,ref?:string){const id=randomUUID();await db.query('insert into auth.users(id,email_confirmed_at,raw_user_meta_data) values($1,$2,$3)',[id,verified?new Date().toISOString():null,JSON.stringify({first_name:'Test',referral_code:ref})]);return id;}
async function scan(owner:string|null,guest='testhash'){return one<{id:string}>("insert into website_scans(user_id,guest_hash,url) values($1,$2,'https://example.com/') returning id",[owner,owner?null:guest]);}
async function complete(id:string){const s=await one<{id:string;attempts:number}>('select * from take_scan($1)',[id]);await db.query('select complete_scan($1,$2,$3,$4,$5)',[id,s.attempts,JSON.stringify({overall:75,scores:{SEO:75},issues:[]}),JSON.stringify({private:'premium content'}),'[]']);}
async function totals(){return one<{registered_users:number;completed_scans:number;reports_generated:number}>('select * from platform_totals');}
beforeAll(async()=>{db=new PGlite({extensions:{pgcrypto}});await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to authenticated,anon,service_role;grant execute on function auth.uid() to authenticated,anon,service_role;`);for(const file of readdirSync('supabase/migrations').filter(f=>f.endsWith('.sql')).sort())await db.exec(readFileSync(`supabase/migrations/${file}`,'utf8'));});
afterAll(async()=>{await db?.close();});
describe('actual PostgreSQL migrations and business invariants',()=>{
 it('counts a verified registration once, excluding unverified users',async()=>{const before=await totals();const id=await user(false);expect((await totals()).registered_users).toBe(before.registered_users);await db.query('update auth.users set email_confirmed_at=now() where id=$1',[id]);await db.query('update auth.users set email_confirmed_at=now() where id=$1',[id]);expect((await totals()).registered_users).toBe(before.registered_users+1);});
 it('atomically records successful scan and report exactly once',async()=>{const id=await user();const s=await scan(id);const before=await totals();await complete(s.id);const retry=await one<{complete_scan:boolean}>('select complete_scan($1,1,$2,$3,$4)',[s.id,'{}','{}','[]']);expect(retry.complete_scan).toBe(false);expect((await totals()).completed_scans).toBe(before.completed_scans+1);expect((await totals()).reports_generated).toBe(before.reports_generated+1);});
 it('failed and cancelled scans never increase completion/report counters',async()=>{const owner=await user();const before=await totals();const failed=await scan(owner),cancelled=await scan(owner);await db.query("update website_scans set status='failed' where id=$1",[failed.id]);await db.query("update website_scans set status='cancelled' where id=$1",[cancelled.id]);await db.query('select complete_scan($1,0,$2,$3,$4)',[cancelled.id,'{}','{}','[]']);expect((await totals()).completed_scans).toBe(before.completed_scans);expect((await totals()).reports_generated).toBe(before.reports_generated);});
 it('claims guest scans only with the matching unexpired token and cannot steal owned scans',async()=>{const a=await user(),b=await user(),s=await scan(null,'correct-token');await complete(s.id);expect((await one<{claim_scan:boolean}>('select claim_scan($1,$2,$3)',[s.id,'wrong',a])).claim_scan).toBe(false);expect((await one<{claim_scan:boolean}>('select claim_scan($1,$2,$3)',[s.id,'correct-token',a])).claim_scan).toBe(true);expect((await one<{claim_scan:boolean}>('select claim_scan($1,$2,$3)',[s.id,'correct-token',b])).claim_scan).toBe(false);expect((await one<{user_id:string}>('select user_id from reports where scan_id=$1',[s.id])).user_id).toBe(a);});
 it('requires verified email plus completed scan and five unique referrals for discount',async()=>{const referrer=await user();const code=(await one<{referral_code:string}>('select referral_code from profiles where id=$1',[referrer])).referral_code;const invited=await user(false,code);const initial=await scan(invited);await complete(initial.id);expect((await one<{status:string}>('select status from referrals where referred_id=$1',[invited])).status).toBe('pending');await db.query('update auth.users set email_confirmed_at=now() where id=$1',[invited]);await db.query('select verify_referral($1)',[invited]);for(let i=0;i<4;i++){const u=await user(true,code);const s=await scan(u);await complete(s.id);await db.query('select verify_referral($1)',[u]);}expect((await one<{n:number}>("select count(*)::int n from referrals where referrer_id=$1 and status='verified'",[referrer])).n).toBe(5);expect((await one<{amount_cents:number}>('select amount_cents from discounts where user_id=$1',[referrer])).amount_cents).toBe(50);await expect(db.query('insert into referrals(referrer_id,referred_id) values($1,$1)',[referrer])).rejects.toThrow();await expect(db.query('insert into referrals(referrer_id,referred_id) values($1,$2)',[referrer,invited])).rejects.toThrow();await db.exec('update app_settings set stripe_enabled=true');const s=await scan(referrer);await complete(s.id);const r=await one<{id:string}>('select id from reports where scan_id=$1',[s.id]);const p=await one<{amount_cents:number;discount_cents:number}>("select * from reserve_payment($1,$2,'stripe')",[referrer,r.id]);expect(p.amount_cents).toBe(150);expect(p.discount_cents).toBe(50);});
 it('verifies exact amount, idempotency, full refund revocation and RLS isolation',async()=>{const a=await user(),b=await user(),s=await scan(a);await complete(s.id);const r=await one<{id:string}>('select id from reports where scan_id=$1',[s.id]);await db.exec('update app_settings set stripe_enabled=true');const p=await one<{id:string;amount_cents:number}>("select * from reserve_payment($1,$2,'stripe')",[a,r.id]);expect(p.amount_cents).toBe(200);expect((await one<{id:string}>("select * from reserve_payment($1,$2,'stripe')",[a,r.id])).id).toBe(p.id);
  await expect(db.query("select fulfill_payment($1,'stripe','evt-wrong','tx-1',150,'USD')",[p.id])).rejects.toThrow('Payment mismatch');
  await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[a]);expect((await db.query('select * from reports')).rows).toHaveLength(0);expect((await db.query<{user_id:string}>('select * from website_scans')).rows.every(row=>row.user_id===a)).toBe(true);await expect(db.query('update profiles set is_admin=true where id=$1',[a])).rejects.toThrow();await expect(db.query('select * from app_settings')).rejects.toThrow();await expect(db.query('select admin_analytics(30)')).rejects.toThrow();await expect(db.query("select fulfill_payment($1,'stripe','evt-forged','tx-1',200,'USD')",[p.id])).rejects.toThrow();await db.exec('reset role');
  await db.query("select fulfill_payment($1,'stripe','evt-good','tx-1',200,'USD')",[p.id]);await db.query("select fulfill_payment($1,'stripe','evt-good','tx-1',200,'USD')",[p.id]);expect((await one<{unlocked:boolean}>('select unlocked from reports where id=$1',[r.id])).unlocked).toBe(true);expect((await one<{n:number}>("select count(*)::int n from platform_events where event_key=$1",[`unlock:${p.id}`])).n).toBe(1);
  await db.exec('set role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[b]);expect((await db.query('select * from reports where id=$1',[r.id])).rows).toHaveLength(0);expect((await db.query('select * from payments where id=$1',[p.id])).rows).toHaveLength(0);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[a]);expect((await db.query('select * from reports where id=$1',[r.id])).rows).toHaveLength(1);await db.exec('reset role');await db.query("select refund_payment('tx-1','evt-refund')");expect((await one<{unlocked:boolean}>('select unlocked from reports where id=$1',[r.id])).unlocked).toBe(false);
 });
 it('does not let public roles read private events or aggregate storage directly',async()=>{await db.exec('set role anon');for(const table of ['profiles','website_scans','reports','payments','referrals','platform_events','platform_totals'])await expect(db.query(`select * from ${table}`)).rejects.toThrow();await db.exec('reset role');});
 it('persists rate limits and returns private metrics from authenticated service operations',async()=>{expect((await one<{consume_rate:boolean}>("select consume_rate('unit-key',1,3600)")).consume_rate).toBe(true);expect((await one<{consume_rate:boolean}>("select consume_rate('unit-key',1,3600)")).consume_rate).toBe(false);const id=await user();expect((await one<{personal_metrics:{websites:number}}>('select personal_metrics($1)',[id])).personal_metrics.websites).toBe(0);const analytics=await one<{admin_analytics:{growth:unknown[]}}>('select admin_analytics(30)');expect(analytics.admin_analytics.growth.length).toBeGreaterThan(0);});
 it('upgrades an installed populated repository schema with the complete SQL file',async()=>{
  const before=await totals();
  const reports=await db.query('select id,content,unlocked from reports order by id');
  await db.exec(readFileSync('supabase/final-production-setup.sql','utf8'));
  expect(await totals()).toEqual(before);
  expect((await db.query('select id,content,unlocked from reports order by id')).rows).toEqual(reports.rows);
 });
});
