'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowRight, GitFork as Github, LockKeyhole } from 'lucide-react';
import { safeNextPath } from '@/lib/auth/redirect';
import { browserDb } from '@/lib/supabase/browser';
export type AuthMode='sign-in'|'sign-up'|'forgot-password'|'reset-password';
export function AuthForm({mode,next='/dashboard'}:{mode:AuthMode;next?:string}){const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const router=useRouter();const titles={'sign-in':'Welcome back.','sign-up':'Your next chapter starts here.','forgot-password':'Let’s get you back in.','reset-password':'Choose a new password.'};const signInWithGithub=async()=>{setBusy(true);setError('');const {error}=await browserDb().auth.signInWithOAuth({provider:'github',options:{redirectTo:`${window.location.origin}/auth/callback?next=${encodeURIComponent(safeNextPath(next))}`}});if(error){setError(error.message);setBusy(false);}};return <div className="auth-card"><div className="feature-icon"><LockKeyhole size={20}/></div><h1>{titles[mode]}</h1><p>{mode==='sign-up'?'Create your private workspace for better websites.':mode==='forgot-password'?'We’ll email you a secure password reset link.':mode==='reset-password'?'Use at least 12 characters for a strong password.':'Sign in to your reports, websites, and next steps.'}</p>{mode==='sign-in'&&<><button type="button" className="button" onClick={signInWithGithub} disabled={busy}><Github size={14}/>{busy?'Connecting…':'Continue with GitHub'}</button><p>or continue with email</p></>}<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');const form=new FormData(e.currentTarget);const email=String(form.get('email')||'');const password=String(form.get('password')||'');try{
 if(mode==='sign-up'){const r=await fetch('/api/auth/signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,firstName:form.get('firstName')})});const data=await r.json();if(!r.ok)throw new Error(data.error);setMessage(data.message);}
 else{const db=browserDb();if(mode==='sign-in'){const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error;router.push(safeNextPath(next));router.refresh();}else if(mode==='forgot-password'){const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/auth/callback?next=/auth/reset-password`});if(error)throw error;setMessage('If an account exists for that email, a reset link is on its way.');}else{const {error}=await db.auth.updateUser({password});if(error)throw error;setMessage('Password updated. You can return to your dashboard.');}}
 }catch(e){setError(e instanceof Error?e.message:'Unable to complete this request.');}finally{setBusy(false);}}}>{mode==='sign-up'&&<label className="field">First name<input className="input" name="firstName" autoComplete="given-name" required maxLength={80}/></label>}{mode!=='reset-password'&&<label className="field">Email address<input className="input" name="email" type="email" autoComplete="email" required placeholder="you@example.com"/></label>}{mode!=='forgot-password'&&<label className="field">Password<input className="input" name="password" type="password" autoComplete={mode==='sign-in'?'current-password':'new-password'} required minLength={mode==='sign-in'?1:12} maxLength={128}/>{mode==='sign-up'&&<small>At least 12 characters.</small>}</label>}{mode==='sign-up'&&<p style={{fontSize:11}}>By creating an account, you agree to our <Link className="inline-link" href="/terms">Terms</Link> and <Link className="inline-link" href="/privacy">Privacy Policy</Link>.</p>}{error&&<div className="error" role="alert">{error}</div>}{message&&<div className="notice" role="status">{message}</div>}<button className="button primary" disabled={busy}>{busy?'Please wait…':mode==='sign-in'?'Sign in':mode==='sign-up'?'Create account':mode==='forgot-password'?'Send reset link':'Update password'}<ArrowRight size={14}/></button></form><div className="auth-links"><Link href={mode==='sign-in'?`/auth/sign-up?next=${encodeURIComponent(next)}`:'/auth/sign-in'}>{mode==='sign-in'?'Create an account':'Back to sign in'}</Link><Link href={mode==='sign-in'?'/auth/forgot-password':'/dashboard'}>{mode==='sign-in'?'Forgot password?':'Your dashboard'}</Link></div></div>;}
export function Logout(){const [busy,setBusy]=useState(false),[error,setError]=useState('');const router=useRouter();return <div><button className="button small" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const {error}=await browserDb().auth.signOut();if(error)throw error;router.push('/');router.refresh();}catch{setError('Unable to sign out. Please try again.');}finally{setBusy(false);}}}>{busy?'Signing out…':'Sign out'}</button>{error&&<p className="error" role="alert">{error}</p>}</div>;}
