'use client';
import { useEffect, useState } from 'react';
import { Users, Globe2, FileText, CheckCircle2, UserRound } from 'lucide-react';
import type { PublicStats } from '@/types';
import { brand } from '@/lib/config';
function useStats(){const [stats,setStats]=useState<PublicStats|null>(null);useEffect(()=>{let active=true;async function refresh(){try{const response=await fetch('/api/public/stats');if(response.ok&&active)setStats(await response.json());else if(active)setStats(null);}catch{if(active)setStats(null);}}void refresh();const timer=setInterval(refresh,30000);return()=>{active=false;clearInterval(timer);};},[]);return stats;}
function Count({value}:{value:number}){const [display,setDisplay]=useState(value);useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;let frame:number;const start=performance.now();function tick(now:number){const fraction=Math.min(1,(now-start)/700);setDisplay(Math.round(value*(1-Math.pow(1-fraction,3))));if(fraction<1)frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[value]);return <>{display.toLocaleString()}</>;}
export function HeroProof(){const stats=useStats();return <div className="social-proof"><div className="avatars" aria-hidden="true">{[0,1,2].map(n=><span key={n} className="avatar"><UserRound size={14}/></span>)}</div><span>{stats?`${stats.registeredUsers.toLocaleString()} verified website owners in our community.`:'Your next improvement starts with a little clarity.'}</span></div>;}
export function Community({dashboard=false}:{dashboard?:boolean}){const stats=useStats();return <div className="stats-shell"><div className="stats-heading"><strong>{dashboard?`${brand.name} Community`:'A growing community. Real progress.'}</strong><small><span className="dot"/>{stats?'Live platform statistics':'Statistics currently unavailable'}</small></div><div className="stats-grid">{[{key:'registeredUsers',label:'Registered users',Icon:Users},{key:'completedScans',label:'Website analyses',Icon:Globe2},{key:'reportsGenerated',label:'Reports generated',Icon:FileText}].map(({key,label,Icon})=><div className="stat" key={key}><Icon size={18}/><strong>{stats?<Count value={stats[key as keyof PublicStats]}/>:<span aria-label="Unavailable">—</span>}</strong><span>{label}</span></div>)}</div>{dashboard&&<CommunityGrowth/>}</div>;}
function CommunityGrowth(){const [points,setPoints]=useState<{date:string;scans:number}[]>([]);useEffect(()=>{let active=true;async function load(){try{const r=await fetch('/api/public/growth');if(r.ok&&active)setPoints(await r.json());}catch{}}void load();const timer=setInterval(load,60000);return()=>{active=false;clearInterval(timer);};},[]);if(!points.length)return null;const max=Math.max(1,...points.map(p=>p.scans));return <div style={{marginTop:20}}><small>Completed analyses · last 14 days</small><div className="chart" style={{height:55,marginTop:10}} role="img" aria-label="Real daily completed website analyses">{points.map(p=><div className="chart-bar" key={p.date} style={{height:`${p.scans/max*100}%`,transition:'height .5s'}} title={`${p.date}: ${p.scans} analyses`}/>)}</div><small>{points.reduce((n,p)=>n+p.scans,0).toLocaleString()} completed in this period</small></div>;}
export function PlatformActivity(){const [events,setEvents]=useState<{message:string;date:string}[]>([]);useEffect(()=>{let active=true;const load=async()=>{try{const r=await fetch('/api/public/activity');if(r.ok&&active)setEvents(await r.json());}catch{}};void load();const timer=setInterval(load,60000);return()=>{active=false;clearInterval(timer);};},[]);if(!events.length)return null;return <div className="panel" style={{marginTop:22}}><h2>Recent platform activity</h2><div className="activity-list">{events.map((event,i)=><div key={i} className="activity-item"><CheckCircle2 size={14}/>{event.message}<small>{event.date}</small></div>)}</div></div>;}
