import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, ArrowRight, Check, ShieldCheck } from 'lucide-react';
import { brand } from '@/lib/config';
import type { CSSProperties, ReactNode } from 'react';
export function Logo(){return <Link href="/" className="brand"><Image src={brand.logo} alt="" width={34} height={34} priority/>{brand.name}</Link>;}
export function Header(){return <header className="header"><div className="container header-inner"><Logo/><nav className="nav" aria-label="Main navigation"><Link href="/#how-it-works">How it works</Link><Link href="/#features">Features</Link><Link href="/#pricing">Pricing</Link><Link href="/#faq">FAQ</Link></nav><div className="header-actions">{process.env.ENABLE_DEMO==='true'&&process.env.NODE_ENV==='development'&&process.env.APP_ENV!=='production'&&<Link className="local-preview-link" href="/demo/dashboard">Explore demo</Link>}<Link href="/auth/sign-in">Sign in</Link><Link className="button primary small" href="/dashboard">Get started <ArrowUpRight size={14}/></Link></div></div></header>;}
export function Footer(){return <footer className="footer"><div className="container"><div className="footer-main"><div><Logo/><p>{brand.tagline}<br/>Understand your website. Make your next improvement count.</p></div><div className="footer-links"><div><strong>Product</strong><Link href="/#features">Features</Link><Link href="/#pricing">Pricing</Link><Link href="/dashboard">Dashboard</Link></div><div><strong>Resources</strong><Link href="/#faq">FAQ</Link><Link href="/contact">Contact</Link><Link href="/disclaimer">Disclaimer</Link></div><div><strong>Legal</strong><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/refunds">Refund policy</Link><Link href="/cookies">Cookie policy</Link></div></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {brand.name}. All rights reserved.</span><span>Built for better websites. No ranking guarantees.</span></div></div></footer>;}
export function ScoreRing({score,label='WEBSITE SCORE'}:{score:number;label?:string}){return <div className="score-ring" style={{'--score':score} as CSSProperties} role="img" aria-label={`${label}: ${score} out of 100`}><div><strong>{score}</strong><small>{label}</small></div></div>;}
export function Bar({label,value}:{label:string;value:number}){return <div><div className="bar-label"><span>{label}</span><span>{value}<small> / 100</small></span></div><div className="bar-track"><div className="bar-fill" style={{width:`${value}%`}}/></div></div>;}
export function Empty({children}:{children:ReactNode}){return <div className="empty"><ShieldCheck size={28}/>{children}</div>;}
export function CheckList({items}:{items:string[]}){return <ul className="check-list">{items.map(item=><li key={item}><Check size={15}/>{item}</li>)}</ul>;}
export function SectionHead({eyebrow,title,children}:{eyebrow:string;title:string;children?:ReactNode}){return <div className="section-head"><div className="eyebrow">{eyebrow}</div><h2>{title}</h2>{children&&<p>{children}</p>}</div>;}
export function DashboardLink(){return <Link href="/dashboard" className="button">Your dashboard <ArrowRight size={14}/></Link>;}
